%YAML:1.0

#The video dir
video_dir: "../data/result.mp4"

#referrence point
left_point.x: 168
left_point.y: 235.5

right_point.x: 486
right_point.y: 235.5

#图像显示停留时间
time: 100  #默认100ms， 0：手动按下'q'键跳至下一帧


#方框坐标
#最下面水平线： 77
#中间水平线： 235
#最上面水平线： 235


#垂直线2： 166
#垂直线4： 343
#垂直线5：486
#最右边垂直线6： 629